In [13]:
import numpy as np

In [14]:
x = np.array([[70, 75, 60]])
x

array([[70, 75, 60]])

In [15]:
y = np.array([[2, 3, 5]])
y

array([[2, 3, 5]])

In [21]:
np.dot(x, y.T)

array([[665]])

In [18]:
y.sum()

10

In [19]:
np.dot(x, y.T) / y.sum()

array([[66.5]])

In [22]:
x = np.array([70, 75, 60])
x

array([70, 75, 60])

In [23]:
y = np.array([2, 3, 5])
y

array([2, 3, 5])

In [24]:
np.dot(x, y)

665