In [1]:
import numpy as np

In [3]:
x = np.array([[1, 2, 3, 4]]).T
x

array([[1],
       [2],
       [3],
       [4]])

In [4]:
y = np.array([[10, 20, 30, 40]]).T
y

array([[10],
       [20],
       [30],
       [40]])

In [5]:
x + y

array([[11],
       [22],
       [33],
       [44]])

In [6]:
z = np.array([[100, 200]]).T
z

array([[100],
       [200]])

In [7]:
y + z

ValueError: operands could not be broadcast together with shapes (4,1) (2,1) 

In [8]:
x

array([[1],
       [2],
       [3],
       [4]])

In [9]:
3 * x

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [10]:
3 + x

array([[4],
       [5],
       [6],
       [7]])