In [1]:
import numpy as np

In [3]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [4]:
y = np.array([[10], [100], [1000]])
y

array([[  10],
       [ 100],
       [1000]])

In [6]:
x.T

array([[1, 2, 3]])

In [7]:
np.dot(x.T, y)

array([[3210]])

In [8]:
x.T @ y

array([[3210]])

In [9]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [10]:
y = np.array([1000, 100, 10])
y

array([1000,  100,   10])

In [11]:
np.dot(x, y)

1230

In [12]:
x @ y

1230